### ISSUE TITLE
Bundling

### ISSUE THREAD

**Issue by bbusemeyer** [lkwagner/autogenv2#5] opened 2017-01-18 18:01 UTC
Particularly for QWalk jobs.

**Comment by lkwagner** [comment] 2017-01-18 18:05
Regarding bundling, I've had a tough time with it on Mira. The issue is that it's hard to predict a priori how many DMC runs you'll actually need to do, and QWalk is pretty particular about having the job divide up in an equal way. Add in the fact that you need to reserve nodes in particular chunks and it's not much better than submitting by hand in the current autogen (and sometimes worse). 

Somehow if we do implement run bundling, it should be a lot smarter, and probably figure out how to bundle knowing these things.

**Comment by bbusemeyer** [comment] 2017-01-18 18:07
What do you mean it's hard to predict the number of DMC jobs?

**Comment by bbusemeyer** [comment] 2017-01-18 18:08
Oh I see, because you set the number of processors when you write the python script. Hmm

**Comment by bbusemeyer** [comment] 2017-01-18 18:08
Maybe have an option that says "use this many processors per job"

**Comment by lkwagner** [comment] 2017-01-18 18:10
Well, suppose I'm running 2 timesteps (.01 and .02) and 2 k-points (1 real and 1 complex). I may not know that there are 2 k-points when I set up the run, but say I do. 

The speed of these calculations is, in order:
t=.02, real
t=.02, complex
t=.01, real
t=.01, complex.

So when I check to see if each has an acceptable error bar, I may need to submit anywhere between 0 and 4 different files. So I cannot just set a static number of processors and expect that to work.

**Comment by bbusemeyer** [comment] 2017-01-18 18:13
I think a "processors per job" option would still work. And I think it'd probably be compatible even for nonbundling.

**Comment by lkwagner** [comment] 2017-04-04 14:36
I'm going to close this because I think it's too complex for where the code currently is.

**Closed as completed by lkwagner** 2017-04-04 14:36 UTC
